import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Auth
    appTitle: 'Health Portal',
    login: 'Login',
    email: 'Email',
    password: 'Password',
    loginButton: 'Sign In',
    welcome: 'Welcome',
    home: 'Home',
    details: 'Details',
    loading: 'Loading...',
    error: 'An error occurred',
    noData: 'No data found',
    logout: 'Logout',
    switchLanguage: 'Arabic',
    loginSubtitle: "Let's get started",
    forgotPassword: 'Forgot Password?',
    signUpPrompt: "Don't have an account?",
    signUp: 'Sign Up',
    emailPlaceholder: 'Email Address',
    passwordPlaceholder: 'Password',
    emailReqError: 'Email address is required.',
    passReqError: 'Password is required.',
    passLenError: 'Password must be at least 8 characters long.',

    // Navigation (Tabs)
    homeTab: 'Home',
    reportsTab: 'Reports',
    healthIdTab: 'Health ID',
    familyHubTab: 'Family Hub',
    quickActionsTab: 'Actions',

    // Home
    hello: 'Hello,',
    liveHealth: 'Live Health Tracker',
    liveIndicator: 'Live',
    heartRate: 'Heart Rate',
    stepCount: 'Steps',
    dailySteps: 'Daily Steps',
    sleep: 'Sleep',
    hours: 'Hours',
    hydration: 'Hydration',
    feelingToday: 'How are you feeling today?',
    moods: ['Amazing', 'Good', 'Okay', 'Low', 'Stressed'],
    familyHealth: 'Family Health',
    viewAll: 'View All',
    add: 'Add',
    quickActions: 'Quick Actions',
    family: 'Family',
    medicine: 'Medicine',
    reports: 'Reports',
    devices: 'Devices',
    healthAI: 'Health AI',
    settings: 'Settings',
    dailyGoals: 'Daily Goals',
    weeklyScore: 'Weekly Health Score',
    excellent: 'Excellent',
    great: 'Great',
    good: 'Good',
    achievements: 'Achievements',
    streak7Day: '7-Day Streak',
    steps10k: '10k Steps',
    healthTips: 'Health Tips For You',
    tipHydrate: 'Stay hydrated! Drink water every hour.',
    tipFruits: 'Add more fruits to your diet today.',
    appointments: 'Appointments',
    upcomingAppts: 'Upcoming Appointments',
    emergContacts: 'Emergency Contacts',
    recentReports: 'Recent Reports',
    overallScore: 'Overall Health Score',
    profileComplete: 'Profile Complete',
    verifiedData: '100% data verified',
    refresh: 'Refresh',

    // Goal Names (Matching Home.jsx data)
    'Steps Goal': 'Steps Goal',
    'Water Intake': 'Water Intake',
    'Calories Burned': 'Calories Burned',

    // Weekdays
    'Mon': 'Mon', 'Tue': 'Tue', 'Wed': 'Wed', 'Thu': 'Thu', 'Fri': 'Fri', 'Sat': 'Sat', 'Sun': 'Sun',

    // Home Vitals & Moods
    feelingAmazing: 'Amazing',
    feelingHappy: 'Happy',
    feelingNeutral: 'Neutral',
    feelingSad: 'Sad',
    feelingWorried: 'Worried',
    excellent: 'Excellent',
    great: 'Great',
    good: 'Good',
    excellentHealth: 'Excellent Health',
    goodHealth: 'Good Health',
    onTrack: 'On Track',
    improving: 'Improving',
    heartRate: 'Heart Rate',
    stepCount: 'Steps',
    dailySteps: 'Daily Steps',
    sleep: 'Sleep',
    hours: 'Hours',
    hydration: 'Hydration',
    bpm: 'bpm',

    // Quick Actions Categories & Items
    qaHeader: 'Quick Actions',
    qaSub: 'Access all features in one place',
    mgmt: 'Health Management',
    homeDash: 'Home Dashboard',
    homeDashSub: 'Your daily health overview',
    quest: 'Health Questionnaire',
    questSub: 'Complete your health profile',
    myProfile: 'My Health Profile',
    myProfileSub: 'Your personalized health ID',
    medTrack: 'Medicine Tracker',
    medTrackSub: 'Track medications and schedules',
    healthAI: 'AI Health Assistant',
    healthAISub: 'Chat with our AI health bot',
    wellness: 'Wellness & Lifestyle',
    wellnessSub: 'Track your daily health',
    familyMon: 'Family & Monitoring',
    familyDash: 'Family Dashboard',
    familyDashSub: 'Monitor family health vitals',
    addMember: 'Add Family Member',
    addMemberSub: 'Register new family members',
    emergSupp: 'Emergency & Support',
    emergServ: 'Emergency Services',
    emergServSub: 'Quick access to emergency help',
    bloodNet: 'Blood Donation Network',
    bloodNetSub: 'Donate blood & save lives',
    medCare: 'Medical Care',
    browseDocs: 'Browse Doctors',
    browseDocsSub: 'Find & book appointments',
    myDocs: 'My Doctors',
    myDocsSub: 'View saved doctors & history',
    medReports: 'Medical Reports',
    medReportsSub: 'Access all medical reports',
    manageApps: 'Manage your appointments',
    syncDevCat: 'Devices & Sync',
    syncDev: 'Connect Devices',
    syncDevSub: 'Sync smart health devices',
    devDash: 'Device Dashboard',
    devDashSub: 'Personal sensor data',
    prefSet: 'Settings & Preferences',
    allSettings: 'All Settings',
    allSettingsSub: 'Manage app preferences',
    personalDetails: 'Personal Details',
    personalDetailsSub: 'Update your information',
    security: 'Security',
    securitySub: 'Manage security settings',
    privacy: 'Privacy',
    privacySub: 'Control your privacy',
    notifications: 'Notifications',
    notificationsSub: 'Custom app notifications',
    accessibility: 'Accessibility',
    accessibilitySub: 'Accessibility options',
    healthPref: 'Health Preferences',
    healthPrefSub: 'Set health goals & preferences',
    medRec: 'Medical Records',
    medRecSub: 'Manage medical records',

    // Medicine Tracker
    medTitle: 'Medicine Tracker',
    medSubtitle: 'Stay on top of your medications',
    taken: 'Taken',
    missed: 'Missed',
    upcoming: 'Upcoming',
    yourMeds: 'Your Medications',
    nextDose: 'Next dose',
    supply: 'Supply',
    twiceDaily: 'Twice daily',
    onceDaily: 'Once daily',
    threeTimesDaily: 'Three times daily',
    takenToday: 'Taken today',
    tomorrow: 'Tomorrow',

    // Accessibility
    languageSelector: 'Language Selection',
    appLanguage: 'App Language',
    appearance: 'Appearance',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',

    // Wellness Hub
    wellnessHub: 'Wellness Hub',
    wellnessSub: 'Track your daily health & lifestyle',
    todayProgress: "Today's Progress",
    wellnessCats: 'Wellness Categories',
    calories: 'Calories',
    nutrition: 'Nutrition',
    nutritionSub: 'Track meals & calories',
    exercise: 'Exercise',
    exerciseSub: 'Log workouts & activity',
    mindfulness: 'Mindfulness',
    mindfulnessSub: 'Meditation & breathing',
    goalsSub: 'Set & track wellness goals',
    mealsToday: '3 meals today',
    exerciseTime: '45 min today',
    breathTime: '10 min today',
    activeGoals: '4 active goals',
    recentAchieve: 'Recent Achievements',
    waterChampion: 'Water Champion',
    earlyBird: 'Early Bird',
    dailyWellnessTip: 'Daily Wellness Tip',
    hydrationTipLong: 'Stay hydrated! Aim for 8 glasses of water throughout the day. Your body performs best when properly hydrated.',

    // Water Intake
    waterIntakeTitle: 'Water Intake',
    waterIntakeSub: 'Hydration tracker',
    ofGlasses: '{x} of {y} glasses',
    quickAdd: 'Quick Add',
    small: 'Small',
    glass: 'Glass',
    bottle: 'Bottle',
    large: 'Large',
    customAmount: 'Custom Amount',
    tapAdjust: 'Tap +/- to adjust',
    todayLog: "Today's Log",
    weeklyProgress: 'Weekly Progress',
    avgDaily: 'Avg Daily',
    daysGoalMet: 'Days Goal Met',
    successRate: 'Success Rate',
    hydrationTip: 'Hydration Tip',
    hydrationTipMsg: 'Drinking water before bed significantly improves sleep quality.',

    // Steps
    stepsTrackerTitle: 'Step Counter',
    stepsTrackerSub: 'Activity monitoring',
    goalLabel: 'Goal:',
    activeNow: 'Active Now',
    minUnit: 'm',
    active: 'active',
    distLabel: 'distance',
    tripsLabel: 'trips',
    weeklyActivity: 'Weekly Activity',
    movementHistory: 'Movement History',
    viewMap: 'View Map',
    morningWalk: 'Morning Walk',
    afternoonTrip: 'Afternoon Trip',
    healthType: 'Health',
    travelType: 'Travel',
    topWalker: 'Top Walker',
    peakEnergy: 'Peak Energy',
    setDailyGoal: 'Set Daily Goal',
    targetSteps: 'Target Steps',
    stepsGoalHint: 'Aiming for 10,000 steps is great for heart health.',
    updateGoal: 'Update Goal',
    cancel: 'Cancel',

    // Nutrition
    nutritionTitle: 'Nutrition',
    todayCalories: "Today's Calories",
    of: 'of',
    kcal: 'kcal',
    remaining: 'remaining',
    kcalLeft: 'kcal left',
    macronutrients: 'Macronutrients',
    protein: 'Protein',
    carbs: 'Carbs',
    fats: 'Fats',
    todayMeals: "Today's Meals",
    snack: 'Snack',
    drink: 'Drink',
    dessert: 'Dessert',
    weeklyCalories: 'Weekly Calories',
    avgDailyIntake: 'Average Daily Intake',
    nutritionTip: 'Nutrition Tip',
    nutritionTipMsg: 'High protein breakfasts keep you full for longer.',

    // Sleep 
    sleepTrackerTitle: 'Sleep Tracker',
    sleepTrackerSub: 'Monitor rest & quality',
    lastNightSleep: "Last Night's Sleep",
    hoursUnit: 'h',
    bedtime: 'Bedtime',
    wakeUp: 'Wake Up',
    sleepStages: 'Sleep Stages',
    awake: 'Awake',
    rem: 'REM',
    lightSleep: 'Light',
    deepSleep: 'Deep',
    sleepMetrics: 'Sleep Metrics',
    sleepScore: 'Sleep Score',
    avgHeartRate: 'Avg Heart Rate',
    restfulness: 'Restfulness',
    weeklySleep: 'Weekly Sleep',
    avgSleep: 'Avg Sleep',
    avgQuality: 'Avg Quality',
    goalDays: 'Goal Days',
    sleepBetter: 'Sleep Better',
    tipSleepSchedule: 'Keep a consistent schedule',
    tipAvoidScreens: 'Avoid screens before bed',
    tipCoolRoom: 'Keep your room cool',
    tipLimitCaffeine: 'Limit caffeine intake',
    setSleepSchedule: 'Set Sleep Schedule',

    // Mindfulness 
    mindfulnessTitle: 'Mindfulness',
    breathControl: 'Breath Control',
    incBreathQuality: 'Improve breath quality',
    startBreathing: 'Start Breathing',
    dailyMeditations: 'Daily Meditations',
    stressRelief: 'Stress Relief',
    focusSession: 'Focus Session',
    dailyStreak: 'Daily Streak',

    // Health AI
    aiGreeting: "Hello! I'm your personal AI Health Assistant. I'm here to help you with questions about your diet, nutrition, fitness, wellness, and overall health. How can I assist you today?",
    quickQsLabel: 'Quick questions:',
    q1: 'What should I eat for breakfast?',
    q2: 'How many calories should I consume?',
    q3: 'How much water should I drink daily?',
    q4: 'How can I improve my heart health?',
    q5: 'Foods that boost brain function?',
    q6: 'Tips for better sleep?',
    aiPlaceholder: 'Ask me about your health...',
    aiResponseMock: "That's a great question! Based on your health profile, I recommend focusing on protein-rich meals and maintaining consistent hydration. Would you like a detailed plan?",

    // Reports
    reportsTitle: 'Medical Reports',
    searchReports: 'Search reports...',
    total: 'Total',
    diag: 'Diagnosis',
    shareReport: 'Share Medical Report',
    view: 'View',
    download: 'Download',
    share: 'Share',

    // Report Types & Diagnoses
    reportCardiology: 'Cardiology Report',
    reportPhysical: 'Physical Examination',
    reportLab: 'Lab Results',
    reportNeurology: 'Neurology Report',
    reportOrthopedic: 'Orthopedic Report',
    reportDental: 'Dental Report',
    reportEye: 'Eye Examination',
    reportDermatology: 'Dermatology Report',
    diagHypertension: 'Mild Hypertension',
    diagHealthy: 'Perfectly Healthy',
    diagCholesterol: 'High Cholesterol',
    diagNeurological: 'Normal Neurological',
    diagOrthopedic: 'Mild Scoliosis',
    diagDental: 'Standard Cleaning',
    diagVision: 'Vision Correction',
    diagSkin: 'Eczema Check',
    attention: 'Attention',
    total: 'Total',
    complete: 'Complete',
    diag: 'Diagnosis',
    reportPreview: 'Report Preview',
    searchInReport: 'Search in report...',
    generalCheckupReport: 'General Check-up Report',
    patientDetails: 'Patient Details',
    vitals: 'Vitals',
    docObservations: "Doctor's Observations",
    notesNextSteps: 'Notes and Next Steps',
    name: 'Name',
    dob: 'DOB',
    gender: 'Gender',
    age: 'Age',
    me: 'Me',
    selectDate: 'Select Date',
    camera: 'Camera',
    
    // Lifestyle & DNA
    smoking: 'Smoking',
    alcoholLevel: 'Alcohol Level',
    dnaSampleType: 'DNA Sample Type',
    activityLevel: 'Activity Level',
    dietType: 'Diet Type',
    sleepDuration: 'Sleep Duration',

    // Detailed Vitals (Reports)
    bloodPressureLabel: 'Blood Pressure',
    pulseLabel: 'Pulse',
    tempLabel: 'Temperature',
    respiratoryRate: 'Respiratory Rate',
    bpm: 'bpm',
    weight: 'Weight',
    height: 'Height',

    // Appointments & Reminders
    activeReminders: 'Active Reminders',
    myMedicine: 'My Medicine',
    upcomingReminders: 'Upcoming Reminders',
    inXHours: 'In {x} hours',
    quickStats: 'Quick Stats',
    reminders: 'Reminders',
    deleteReminderTitle: 'Delete Reminder?',
    deleteReminderMsg: 'Are you sure you want to delete this reminder?',
    deleteNow: 'Delete Now',
    asPrescribed: 'As prescribed',
    all: 'All',

    // Share
    copyLinkDesc: 'Copy link or share via social media',
    copied: 'Copied',
    copy: 'Copy',
    more: 'More',
    whatsapp: 'WhatsApp',
    telegram: 'Telegram',
    email: 'Email',

    // Family Hub
    dataSharingAgreem: 'Data Sharing Agreement',
    familyDataSub: 'Important information about family health data',
    fullVis: 'Full Data Visibility',
    fullVisSub: "All family members you add will have access to view each other's complete health information, including medical records, vital signs, medications, and reports.",
    sharedDash: 'Shared Health Dashboard',
    sharedDashSub: 'Every member will appear on your family health dashboard, and their health data will be continuously monitored and displayed.',
    consentReq: 'Consent Required',
    consentReqSub: 'By adding a family member, you confirm that you have their consent to share their health information on this platform.',
    iAgreeTerms: "I understand and agree that all family members will have access to view each other's complete health data, and I have obtained consent from the person I'm adding.",
    agreeCont: 'I Agree, Continue',
    memberDetails: 'Member Details',
    age: 'Age',
    gender: 'Gender',
    relationship: 'Relationship',
    inviteSent: 'Invite Sent',
    online: 'Online',
    offline: 'Offline',
    typeMessage: 'Type a message...',
    familyHubChat: 'Family Hub Chat',
    searchFamily: 'Search family members...',
    familyGroup: 'Family Group',
    previewAR: 'Explore AR',
    welcomeAR: 'Welcome to Synced AR EXPERIENCE',
    viewInSpace: 'View in your space',
    groupChatSub: 'Chat with everyone at once',
    privateMessages: 'Private Messages',
    participants: 'participants',
    videoCallInc: 'Incoming Video Call...',
    endCall: 'End Call',
    chatSysMsg: 'Family Chat started. Be kind!',
    chatAutoReply: "Thanks for the message! I'm busy right now but I'll get back to you soon.",
    healthy: 'Healthy',
    yearsOld: 'years old',
    managePrivacy: 'Manage Data Sharing & Privacy',
    live: 'Live',
    bpm: 'bpm',
    good: 'Good',
    todayMood: "Today's Mood",
    allergies: 'Allergies',
    healthId: 'Health ID',
    historyTitle: 'History',
    insurance: 'Insurance',
    medicalHist: 'Medical History',
    files: 'Files',
    daily: 'Daily',
    uploadNewReport: 'Upload New Report',
    privacySharing: 'Privacy & Sharing',
    privacyDesc: 'Control what health data this member can view from your profile.',
    overallSharing: 'Overall Sharing Level',
    familyOnly: 'Family members only',
    emergDocs: 'Emergency & Doctors',
    fullAccess: 'Full Access',
    noAccess: 'No Access',
    youPoked: 'You Poked',
    pokeNote: "They'll receive a notification shortly.",
    privacyUpdated: 'Privacy preferences updated!',

    // Emergency Relations
    relWife: 'Wife',
    relBrother: 'Brother',
    relDoctor: 'Primary Physician',
    emergencyTitle: 'Emergency',
    emergencySubtitle: 'Quick access to emergency services',
    medicalAlerts: 'Medical Alerts',
    criticalInfo: 'Critical Information',
    bloodType: 'Blood Type',
    dnaType: 'DNA Type',
    age: 'Age',
    weight: 'Weight',
    yearsOld: 'years old',
    kg: 'kg',
    allergies: 'Allergies',
    currentMedications: 'Current Medications',
    emergencyContacts: 'Emergency Contacts',
    nearbyHospitals: 'Nearby Hospitals',
    er: 'ER',
    callAction: 'Call',
    directionsAction: 'Directions',

    // Doctors & Specialties
    findDoctors: 'Find Doctors',
    bookSpecialists: 'Book Specialist Appointments',
    searchDoctorsSpec: 'Search doctors, specialties...',
    allSpecialties: 'All Specialties',
    viewMyDoctors: 'View My Doctors',
    availableToday: 'Available Today',
    availableTomorrow: 'Available Tomorrow',
    nextDoseTime: 'Next',
    cardiology: 'Cardiology',
    neurology: 'Neurology',
    orthopedics: 'Orthopedics',
    general: 'General',
    addFamilyMember: 'Add Family Member',
    enterHealthInfo: 'Enter their health information',
    fullNameLabel: 'Full Name',
    enterFullName: 'Enter full name',
    selectRelationship: 'Select Relationship',
    dobLabel: 'Date of Birth',
    genderLabel: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    phoneNum: 'Phone Number',
    bloodType: 'Blood Type',
    selectBloodType: 'Select Blood Type',
    knownAllergies: 'Known Allergies',
    listAllergies: 'List any allergies',
    saveFinish: 'Save & Finish',
    fillRequired: 'Please fill in all required fields',
    relationships: {
      Father: 'Father',
      Mother: 'Mother',
      Son: 'Son',
      Daughter: 'Daughter',
      Grandfather: 'Grandfather',
      Grandmother: 'Grandmother',
      Brother: 'Brother',
      Sister: 'Sister',
      Other: 'Other'
    },
    chooseAvatar: 'Choose Avatar',
    selectProfilePic: 'Select a profile picture for you',
    avatarList: {
      Man: 'Man',
      Woman: 'Woman',
      Boy: 'Boy',
      Girl: 'Girl',
      'Elderly Man': 'Elderly Man',
      'Elderly Woman': 'Elderly Woman',
      Baby: 'Baby',
      Person: 'Person',
      Doctor: 'Doctor',
      Nurse: 'Nurse',
      Child: 'Child',
      Elder: 'Elder'
    },
    relationships: {
      Father: 'Father',
      Mother: 'Mother',
      Son: 'Son',
      Daughter: 'Daughter',
      Grandfather: 'Grandfather',
      Grandmother: 'Grandmother',
      Brother: 'Brother',
      Sister: 'Sister',
      Other: 'Other'
    },
    chooseAvatar: 'Choose Avatar',
    selectProfilePic: 'Select a profile picture for you',
    avatarList: {
      Man: 'Man',
      Woman: 'Woman',
      Boy: 'Boy',
      Girl: 'Girl',
      'Elderly Man': 'Elderly Man',
      'Elderly Woman': 'Elderly Woman',
      Baby: 'Baby',
      Person: 'Person',
      Doctor: 'Doctor',
      Nurse: 'Nurse',
      Child: 'Child',
      Elder: 'Elder'
    },
    familyAch: 'Family Achievements',
    stepChart: 'Weekly Step Chart',
    goalSteps: 'Goal: 10k Steps',
    achBadges: 'Achievements & Badges',
    tenKClub: '10k club',
    workouts: 'Workouts',
    congratulate: 'Congratulate',
    sent: 'Sent',
    congratsSentTo: 'Congratulations sent to',
    logIn: 'Log In',
    signup: 'Sign Up',
    letsGetStarted: 'Let’s get started',
    emailAddress: 'Email Address',
    passwordLabel: 'Password',
    eightChars: '8+ Chars',
    numbers: 'Numbers',
    symbols: 'Symbols',
    forgetPassQ: 'Forget Password?',
    dontHaveAccount: 'Don’t have an account?',
    signUpAction: 'Sign Up',
    pleaseEnterEmail: 'Please enter any email to continue',
    pleaseEnterPassword: 'Please enter a password',
    skip: 'Skip',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    termsService: 'Terms of Service',
    privacyPolicyAuth: 'Privacy Policy',
    pleaseSignUp: 'Please Sign Up to Log In',
    firstName: 'First Name',
    lastName: 'Last Name',
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    invalidEmail: 'Invalid email address',
    minEightChars: 'Minimum 8 characters required',
    emailExists: 'Email already exists',
    forgetPassTitle: 'Forget Password?',
    enterVerifCode: 'Enter verification code',
    sentToEmail: 'sent to your email',
    resetPass: 'Reset Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passNotMatch: 'Passwords do not match or too short',
    rememberedPass: 'I remembered my password.',
    confirmationTitle: 'Confirmation',
    enterCodeSentTo: 'Enter code sent to',
    incorrectCode: 'Incorrect code. Please try again.',
    didntReceiveCode: 'Didn’t receive code?',
    resendCode: 'Resend Code',
    verify: 'Verify',
    confirmedTitle: 'Confirmed',
    phoneVerified: 'Your phone number has been successfully verified.',
    getStarted: 'Get Started',
    registrationTitle: 'Registration',
    enterPhoneVerify: 'Enter your phone number to verify your account.',
    phoneNumberPlaceholder: 'Phone Number',
    continue: 'Continue',
    countries: {
      Egypt: 'Egypt',
      Saudi: 'Saudi',
      UAE: 'UAE'
    },
    welcomeTitle: 'Welcome to SYNCED',
    welcomeDesc: 'Your comprehensive health and wellness ecosystem. Everything you need, centralized in one intelligent platform.',
    trackTitle: 'Track & Monitor',
    trackDesc: 'Log your medicines, monitor your daily vitals, and keep all your medical records securely in your pocket.',
    aiTitle: 'AI Health Assistant',
    aiDesc: 'Chat with our smart AI for instant symptom analysis and seamlessly connect with top medical professionals.',
    familyTitle: 'Family & Emergency',
    familyDesc: 'Link your loved ones to a shared Family Hub, and get immediate access to one-tap emergency support.',
    loginOrRegister: 'Login or Register',
    orLabel: 'OR',
    skipToQuiz: 'Skip to Virtual Quiz',
    basicInfoTitle: 'Basic Information',
    enterMedNameDosage: 'Enter medicine name and dosage',
    medBoxPhoto: 'Medicine Box Photo',
    takeBoxPhoto: 'Take a picture of the box',
    helpsIdentify: 'Helps identify medicine correctly',
    retake: 'Retake',
    captured: 'Captured',
    medName: 'Medicine Name',
    aspirinEx: 'e.g., Aspirin',
    doseAmount: 'Dose Amount',
    unit: 'Unit',
    colorTheme: 'Color Theme',
    camError: 'Could not access camera. Please check permissions.',
    dosageScheduleTitle: 'Dosage & Schedule',
    setFreqTiming: 'Set frequency and timing',
    frequencyLabel: 'Frequency',
    timeSlots: 'Time Slots',
    durationDays: 'Treatment Duration (days)',
    frequencyOptions: {
      'Once daily': 'Once daily',
      'Twice daily': 'Twice daily',
      'Three times daily': 'Three times daily',
      'Four times daily': 'Four times daily',
      'Custom schedule': 'Custom schedule'
    },
    remindersTitle: 'Reminders',
    configNotifs: 'Configure notifications',
    enableReminders: 'Enable Reminders',
    getNotifiedTime: "Get notified when it's time",
    willRecieveRemindersAt: "You'll receive reminders at:",
    additionalDetailsTitle: 'Additional Details',
    finalCustomization: 'Final customization',
    notesOptional: 'Notes (Optional)',
    notesPlaceholder: 'E.g., Take with food, avoid alcohol...',
    summary: 'Summary',
    schedule: 'Schedule',
    duration: 'Duration',
    addMedicineAction: 'Add Medicine',
    enabled: 'Enabled',
    disabled: 'Disabled',

    // Settings & Accessibility
    settings: 'Settings',
    manageAccount: 'Manage Account',
    profile: 'Profile',
    securityDetails: 'Security details',
    accessibility: 'Accessibility',
    healthAndMedical: 'Health & Medical',
    healthPreferences: 'Health Preferences',
    medicalRecords: 'Medical Records',
    appointmentSettings: 'Appointment Settings',
    deviceConnectivity: 'Device & Connectivity',
    connectedDevices: 'Connected Devices',
    notifications: 'Notifications',
    notificationSettings: 'Notification Settings',
    legalPrivacy: 'Legal and Privacy',
    privacySettings: 'Privacy Settings',
    helpCenter: 'Help Center',
    languageSelector: 'Language Selector',
    appLanguage: 'App Language',
    appearance: 'Appearance',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    textSize: 'Text Size',
    fontSize: 'Font Size',
    sizeHint: 'This is how your text will appear throughout the app.',
    visualAdjustments: 'Visual Adjustments',
    highContrast: 'High Contrast',
    highContrastDesc: 'Increase color contrast',
    reduceMotion: 'Reduce Motion',
    reduceMotionDesc: 'Minimize animations',
    colorAccessibility: 'Color Accessibility',
    colorBlindMode: 'Color Blind Mode',
    pointerCursor: 'Pointer & Cursor',
    cursorSize: 'Cursor Size',
    audioSpeech: 'Audio & Speech',
    resetToDefault: 'Reset to Default Settings',
    accessibilityDisclaimer: 'These settings help make the app more accessible and easier to use for everyone.',
    
    // Personal/Edit Profile
    personalInformation: 'Personal Information',
    editProfile: 'Edit Profile',
    accountSettings: 'Account Settings',
    healthIdCard: 'Health ID Card',
    shareProfile: 'Share Profile',
    downloadHealthData: 'Download Health Data',
    verifiedAccount: 'Verified Account',
    quickActions: 'Quick Actions',
    email: 'Email',
    phone: 'Phone',
    dob: 'Date of Birth',
    location: 'Location',
    healthInformation: 'Health Information',
    bloodType: 'Blood Type',
    weight: 'Weight',
    height: 'Height',
    bmi: 'BMI',
    allergies: 'Allergies',
    medicalConditions: 'Medical Conditions',
    emergencyContact: 'Emergency Contact',
    contactName: 'Contact Name',
    relationship: 'Relationship',
    phoneNumber: 'Phone Number',
    save: 'Save',
    tapToChange: 'Tap to change photo',

    // Security Details
    securityDetailsTitle: 'Security Details',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePasswordAction: 'Update Password',
    twoFactorAuth: 'Two-Factor Authentication',
    smsAuth: 'SMS Authentication',
    smsAuthDesc: 'Receive codes via text message',
    emailAuth: 'Email Authentication',
    emailAuthDesc: 'Receive codes via email',
    authApp: 'Authenticator App',
    authAppDesc: 'Use an authenticator app',
    biometricSecurity: 'Biometric Security',
    faceId: 'Face ID',
    faceIdDesc: 'Use facial recognition to unlock',
    fingerprint: 'Fingerprint',
    fingerprintDesc: 'Use fingerprint to unlock',
    loginActivity: 'Login Activity',
    activeStatus: 'Active',
    removeAction: 'Remove',

    // Health Preferences
    healthPreferencesTitle: 'Health Preferences',
    healthGoals: 'Health Goals',
    weightManagement: 'Weight Management',
    weightManagementDesc: 'Track weight and set goals',
    fitnessTracking: 'Fitness Tracking',
    fitnessTrackingDesc: 'Monitor daily activity',
    sleepQuality: 'Sleep Quality',
    sleepQualityDesc: 'Track sleep patterns',
    vitalSignsTargets: 'Vital Signs Targets',
    targetHeartRate: 'Target Heart Rate (bpm)',
    bloodPressure: 'Blood Pressure (mmHg)',
    dailyStepsGoal: 'Daily Steps Goal',
    waterIntakeGoal: 'Water Intake Goal (L)',
    nutritionPreferences: 'Nutrition Preferences',
    dietaryRestrictions: 'Dietary Restrictions',
    calorieTracking: 'Calorie Tracking',
    calorieTrackingDesc: 'Monitor daily calorie intake',
    mealReminders: 'Meal Reminders',
    mealRemindersDesc: 'Get reminded for meals',
    savePreferencesAction: 'Save Preferences',

    // Medical Records
    medicalRecordsTitle: 'Medical Records',
    addRecord: 'Add Record',
    searchDocuments: 'Search documents...',
    uploadMedicalRecords: 'Upload Medical Records',
    uploadLimit: 'PDF, JPEG, PNG up to 10MB',
    chooseFiles: 'Choose Files',
    recentRecords: 'Recent Records',
    verified: 'Verified',
    viewAction: 'View',
    downloadAction: 'Download',
    shareAction: 'Share',
    browseByCategory: 'Browse by Category',
    filesCount: 'files',
    noRecordsFound: 'No records found matching your search',
    allRecords: 'All Records',
    labResults: 'Lab Results',
    imaging: 'Imaging',
    prescriptions: 'Prescriptions',
    immunizations: 'Immunizations',
    exams: 'Exams',

    // Appointment Settings
    appointmentSettingsTitle: 'Appointment Settings',
    apptPreferences: 'Preferences',
    defaultApptType: 'Default Appointment Type',
    inPersonVisits: 'In-person visits',
    preferredTimeSlot: 'Preferred Time Slot',
    morningTime: 'Morning (9 AM - 12 PM)',
    autoConfirmAppts: 'Auto-confirm Appointments',
    skipConfirmation: 'Skip confirmation step',
    upcomingAppointments: 'Upcoming Appointments',
    rescheduleAction: 'Reschedule',
    cancelAction: 'Cancel',
    telemedicine: 'Telemedicine',
    appointmentTypes: 'Appointment Types',
    videoConsultations: 'Video Consultations',
    virtualAppts: 'Virtual appointments',
    phoneConsultations: 'Phone Consultations',
    audioOnlyCalls: 'Audio-only calls',
    cancellationPolicy: 'Cancellation Policy',
    gracePeriod: 'Grace Period',
    gracePeriodDesc: 'You can cancel or reschedule appointments up to 24 hours before the scheduled time without any charges. Late cancellations may incur a fee.',
    sendCancellationReminders: 'Send Cancellation Reminders',
    deadlineDesc: '24 hours before deadline',

    // Connected Devices
    connectedDevicesTitle: 'Connected Devices',
    connectNewDevice: 'Connect New Device',
    yourDevices: 'Your Devices',
    connectedStatus: 'Connected',
    inactiveStatus: 'Inactive',
    lastSyncedText: 'Last synced',
    autoSyncEnabled: 'Auto-sync enabled',
    reconnectAction: 'Reconnect',
    syncSettings: 'Sync Settings',
    autoSyncAll: 'Auto-sync All Devices',
    autoSyncDesc: 'Automatically sync when in range',
    backgroundSync: 'Background Sync',
    backgroundSyncDesc: 'Sync data in the background',
    syncFrequency: 'Sync Frequency',
    every30Min: 'Every 30 minutes',
    wifiOnlySync: 'Wi-Fi Only Sync',
    wifiOnlyDesc: 'Sync only when on Wi-Fi',
    dataPermissions: 'Data Permissions',
    heartRateData: 'Heart Rate Data',
    allowAccessDesc: 'Allow apps to access',
    activityFitness: 'Activity & Fitness',
    activityFitnessDesc: 'Steps, calories, workouts',
    sleepData: 'Sleep Data',
    sleepDataDesc: 'Sleep patterns and quality',
    bloodPressureData: 'Blood Pressure',
    bloodPressureDesc: 'BP measurements',
    bloodGlucose: 'Blood Glucose',
    bloodGlucoseDesc: 'Glucose level readings',

    // Notification Settings
    notificationSettingsTitle: 'Notification Settings',
    apptReminders: 'Appointment Reminders',
    apptRemindersDesc: 'Get notified before appointments',
    reminderTiming: 'Reminder Timing',
    reminderTimingDesc: '1 day and 1 hour before',
    apptCancellations: 'Appointment Cancellations',
    apptCancellationsDesc: 'Notify about changes',
    medReminders: 'Medication Reminders',
    medRemindersDesc: 'Get reminded to take medications',
    refillReminders: 'Refill Reminders',
    refillRemindersDesc: 'Alert when refill is needed',
    missedDoseAlerts: 'Missed Dose Alerts',
    missedDoseDesc: 'Alert if a dose is missed',
    dailyHealthSummary: 'Daily Health Summary',
    dailyHealthSummaryDesc: 'Get daily health insights',
    abnormalReadingsAlert: 'Abnormal Readings Alert',
    abnormalReadingsDesc: 'Alert for unusual vital signs',
    goalAchievements: 'Goal Achievements',
    goalAchievementsDesc: 'Celebrate your milestones',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Receive push notifications',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Get updates via email',
    smsNotifications: 'SMS Notifications',
    smsNotificationsDesc: 'Receive text messages',
    marketingCommunications: 'Marketing Communications',
    marketingCommunicationsDesc: 'Tips and health insights',
    quietHours: 'Quiet Hours',
    enableQuietHours: 'Enable Quiet Hours',
    quietHoursDesc: 'Silence non-urgent notifications',
    timeRange: 'Time Range',
    quietHoursRange: '10:00 PM - 7:00 AM',

    // Privacy Settings
    privacySettingsTitle: 'Privacy Settings',
    dataSharing: 'Data Sharing',
    shareWithProviders: 'Share with Healthcare Providers',
    shareWithProvidersDesc: 'Allow doctors to access your data',
    shareWithFamily: 'Share with Family Members',
    shareWithFamilyDesc: 'Let family view your health info',
    researchParticipation: 'Research Participation',
    researchParticipationDesc: 'Contribute to health research',
    anonymousAnalytics: 'Anonymous Analytics',
    analyticsDesc: 'Help improve our services',
    visibilityProfile: 'Visibility & Profile',
    publicProfile: 'Public Profile',
    publicProfileDesc: 'Make profile visible to others',
    showActivityStatus: 'Show Activity Status',
    activityStatusDesc: "Let others see when you're active",
    healthAchievements: 'Health Achievements',
    achievementsDesc: 'Display your accomplishments',
    userDataRights: 'Your Data Rights',
    downloadYourData: 'Download Your Data',
    downloadDataDesc: 'Get a copy of all your information',
    exportMedicalRecords: 'Export Medical Records',
    exportRecordsDesc: 'Download your health records',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyDesc: 'Read our privacy policy',
    termsOfService: 'Terms of Service',
    termsOfServiceDesc: 'Review terms and conditions',
    dataRetention: 'Data Retention',
    autoDataCleanup: 'Automatic Data Cleanup',
    cleanupDesc: 'Your data will be automatically deleted after 7 years of inactivity, as required by medical data retention laws.',
    keepActivityHistory: 'Keep Activity History',
    duration2Years: 'Duration: 2 years',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountDesc: 'Permanently delete your account and all associated data. This action cannot be undone.',
    deleteAccountAction: 'Delete My Account',

    // Home
    liveHealth: 'Live Health',
    feelingToday: 'Feeling Today?',
    excellent: 'Excellent',
    great: 'Great',
    good: 'Good',
    bpm: 'bpm',
    tipHydrate: 'Keep hydrated throughout the day',
    tipFruits: 'Eat more green vegetables and fruits',
    overallScore: 'Overall Score',
    profileComplete: 'Profile Complete',
    verifiedData: '100% Data Verified',
    healthTips: 'Health Tips',
    feelingAmazing: 'Amazing',
    feelingHappy: 'Happy',
    feelingNeutral: 'Neutral',
    feelingSad: 'Sad',
    feelingWorried: 'Worried',

    // Emergency
    emergencyTitle: 'Emergency',
    emergencySubtitle: 'Quick access to emergency services',
    medicalAlerts: 'Medical Alerts',
    criticalInfo: 'Critical Info',
    bloodType: 'Blood Type',
    dnaType: 'DNA Type',
    allergies: 'Allergies',
    currentMedications: 'Current Medications',
    emergencyContacts: 'Emergency Contacts',
    nearbyHospitals: 'Nearby Hospitals',
    er: 'ER',
    callAction: 'Call',
    directionsAction: 'Directions',
    yearsOld: 'yrs',
    kg: 'kg',
    relWife: 'Wife',
    relBrother: 'Brother',
    relDoctor: 'Primary Doctor',

    // Family Hub
    familyHubTitle: 'Family Health Hub',
    familyMembers: 'Family Members',
    remindersCount: 'reminders',
    upcomingCount: 'Upcoming',
    familyChat: 'Family Chat',
    excellentHealth: 'Excellent Health',
    wellnessScoreFull: 'Family Wellness Score & Achievements',
    removeMemberTitle: 'Remove Member?',
    removeMemberConfirm: 'Are you sure you want to remove this member? This action will permanently delete their health records.',
    weeklyBadges: 'Weekly Badges',
    newMessagesCount: 'new',
    medications: 'Medications',
    remove: 'Remove',

    // Health ID
    verified: 'Verified',
    healthIdSubtitle: 'Health ID • Verified Member',
    overallHealthScore: 'Overall Health Score',
    excellentProgress: 'Excellent Progress',
    basicInfo: 'Basic Information',
    currentVitals: 'Current Vitals',
    physicalStats: 'Physical Statistics',
    lifestyleHabits: 'Lifestyle Habits',
    emergencyPriorityInfo: 'Emergency Priority Info',
    chronicConditions: 'Chronic Conditions',
    pastSurgeries: 'Past Surgeries',
    geneticsDna: 'Genetics & DNA',
    geneticRiskFactors: 'Genetic Risk Factors',
    familyMedicalHistory: 'Family Medical History',
    medicalReportsFiles: 'Medical Reports & Files',
    viewAllReports: 'View All Reports',

    // Doctors
    findDoctors: 'Find Doctors',
    bookSpecialists: 'Book appointments with specialists',
    searchDoctorsSpec: 'Search doctors, specialties...',
    allSpecialties: 'All Specialties',
    viewMyDoctors: 'View My Doctors',
    availableToday: 'Available Today',
    availableTomorrow: 'Available Tomorrow',
    nextDoseTime: 'Next',
    myDoctorsTitle: 'My Doctors',
    lastVisit: 'Last Visit',
    nextAppointment: 'Next Appointment',
    notScheduled: 'Not scheduled',
    chat: 'Chat',
    book: 'Book',
    emergencyServices: 'Emergency Services',
    poisonControl: 'Poison Control',
    hospitalHotline: 'Hospital Hotline',

    // Blood Network
    bloodNetworkTitle: 'Blood Network',
    yourBloodType: 'Your Blood Type',
    livesImpacted: 'Lives Impacted',
    nextEligible: 'Next Eligible',
    canDonateTo: 'Can Donate To',
    activeRequests: 'Active',
    criticalRequests: 'Critical',
    nearbyRequests: 'Nearby',
    bloodRequestsTitle: 'Blood Requests',
    nearbyBloodBanks: 'Nearby Blood Banks',
    donationGuidelines: 'Donation Guidelines',
    donationGuidelinesDesc: 'You can donate blood every 56 days. Ensure you are well-rested, hydrated, and have eaten before donating.',

    // Devices & Syncing
    syncingData: 'Syncing Data',
    syncSuccess: 'All health data successfully synced',
    syncWait: 'Please wait while we fetch your data',
    syncDone: 'Done',
    discoverDevices: 'Discover Devices',
    scanningDevices: 'Scanning for nearby devices...',
    pairingModeInfo: 'Make sure Bluetooth is enabled and your device is in pairing mode',

    // Medical Report Upload
    uploadReportTitle: 'Upload Report',
    uploadReportSub: 'Add your medical documents and reports',
    selectFamilyMember: 'Select Family Member',
    viewAllMembers: 'View All Members',
    reportTitle: 'Report Title',
    reportTitleExample: 'e.g., Blood Test Results',
    reportDate: 'Report Date',
    dropFilesHint: 'Drop files here or click to upload',
    fileSelected: 'File selected successfully',
    uploadLimit: 'PDF, JPG, PNG up to 10MB',
    browseFiles: 'Browse Files',
    notesPlaceholderReport: 'Add any extra information about this report.',
    uploadReportAction: 'Upload Report',
    category: 'Category',
    imagingLabel: 'Imaging',
    prescription: 'Prescription',
    checkup: 'Checkup',
    vaccination: 'Vaccination',

    // QuizHero & Onboarding
    onboardingStep: 'Step {x} of {y}',
    quizSkip: 'Skip',
    quizBegin: 'Let\'s Begin',
    quizBack: 'Back',
    quizContinue: 'Continue',
    createHealthIDTitle: 'Create Health ID',
    createHealthIDDesc: 'Let\'s build your personalized health profile in just a few minutes. Your data is secure and helps us provide better care.',
    personalizedCare: 'Personalized Care',
    personalizedCareSub: 'Get health recommendations tailored to you',
    emergencyReady: 'Emergency Ready',
    emergencyReadySub: 'Critical info accessible when needed most',
    trackProgress: 'Track Progress',
    trackProgressSub: 'Monitor your health journey over time',
    tellUsAboutYou: 'Tell us about you',
    basicInfoSub: 'Basic information to get started',
    firstName: 'First Name',
    lastName: 'Last Name',
    firstNamePlaceholder: 'Enter your first name',
    lastNamePlaceholder: 'Enter your last name',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    physicalStatsTitle: 'Physical Stats',
    metricsSub: 'Help us track your health metrics',
    height: 'Height',
    weight: 'Weight',
    medicalHistoryTitle: 'Medical History',
    safetyShortSub: 'Important for your safety',
    allergiesPlaceholder: 'e.g., Penicillin, Peanuts, None',
    conditionsPlaceholder: 'e.g., Diabetes, Hypertension, None',
    medsPlaceholder: 'e.g., Aspirin 100mg, None',
    criticalInfoWarning: 'This information is critical for emergency situations and proper treatment.',
    lifestyleTitle: 'Lifestyle',
    habitsShapeSub: 'Everyday habits that shape your health',
    activityLevel: 'Activity Level',
    dietType: 'Diet Type',
    avgSleep: 'Average Sleep (hours)',
    smokingStatus: 'Smoking Status',
    alcoholConsumption: 'Alcohol Consumption',
    geneticInfoTitle: 'Genetic Info',
    compatibilitySub: 'Important for compatibility',
    emergencyContactTitle: 'Emergency Contact',
    whoContactSub: 'Who should we contact?',
    contactName: 'Contact Name',
    allSetTitle: 'You\'re All Set!',
    successCreatedSub: 'Your personalized health ID has been successfully created.',
    enterMyHub: 'Enter My Health Hub',
    // Lifestyle Options
    sedentary: 'Sedentary',
    light: 'Light',
    moderate: 'Moderate',
    veryActive: 'Very Active',
    regular: 'Regular',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    keto: 'Keto',
    never: 'Never',
    former: 'Former',
    current: 'Current',
    occasionally: 'Occasionally',
    moderately: 'Moderately',
    frequently: 'Frequently',

    // Navigation
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    next: 'Next',
  },
  ar: {
    // Auth
    appTitle: 'بوابة الصحة',
    login: 'تسجيل الدخول',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    loginButton: 'تسجيل الدخول',
    welcome: 'أهلاً بك',
    home: 'الرئيسية',
    details: 'التفاصيل',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ ما',
    noData: 'لم يتم العثور على بيانات',
    logout: 'تسجيل الخروج',
    switchLanguage: 'English',
    loginSubtitle: 'لنبدأ الآن',
    forgotPassword: 'نسيت كلمة السر؟',
    signUpPrompt: 'ليس لديك حساب؟',
    signUp: 'سجل الآن',
    emailPlaceholder: 'البريد الإلكتروني',
    passwordPlaceholder: 'كلمة المرور',
    emailReqError: 'البريد الإلكتروني مطلوب.',
    passReqError: 'كلمة المرور مطلوبة.',
    passLenError: 'يجب أن تتكون كلمة المرور من ٨ أحرف على الأقل.',

    // Navigation (Tabs)
    homeTab: 'الرئيسية',
    reportsTab: 'التقارير',
    healthIdTab: 'الهوية الصحية',
    familyHubTab: 'ملتقى العائلة',
    quickActionsTab: 'الإجراءات',

    // Accessibility
    languageSelector: 'اختيار اللغة',
    appLanguage: 'لغة التطبيق',
    appearance: 'المظهر',
    theme: 'السمة',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',

    // Home
    hello: 'أهلاً بك،',
    liveHealth: 'تتبع الصحة المباشر',
    liveIndicator: 'مباشر',
    heartRate: 'ضربات القلب',
    stepCount: 'الخطوات',
    dailySteps: 'الخطوات اليومية',
    sleep: 'النوم',
    hours: 'ساعة',
    hydration: 'الترطيب',
    feelingToday: 'كيف تشعر اليوم؟',
    moods: ['رائع', 'جيد', 'عادي', 'ضعيف', 'مجهد'],
    familyHealth: 'صحة العائلة',
    viewAll: 'عرض الكل',
    add: 'إضافة',
    quickActions: 'إجراءات سريعة',
    family: 'العائلة',
    medicine: 'الأدوية',
    reports: 'التقارير',
    devices: 'الأجهزة',
    healthAI: 'مساعد الصحة',
    settings: 'الإعدادات',
    dailyGoals: 'الأهداف اليومية',
    weeklyScore: 'النتيجة الصحية الأسبوعية',
    excellent: 'ممتاز',
    great: 'رائع',
    good: 'جيد',
    achievements: 'الإنجازات',
    streak7Day: 'سلسلة ٧ أيام',
    steps10k: '١٠ آلاف خطوة',
    healthTips: 'نصائح صحية لك',
    tipHydrate: 'حافظ على رطوبتك! اشرب الماء كل ساعة.',
    tipFruits: 'أضف المزيد من الفاكهة إلى نظامك الغذائي اليوم.',
    appointments: 'المواعيد',
    upcomingAppts: 'المواعيد القادمة',
    emergContacts: 'جهات اتصال الطوارئ',
    recentReports: 'التقارير الأخيرة',
    overallScore: 'النتيجة الصحية العامة',
    profileComplete: 'الملف الشخصي مكتمل',
    verifiedData: '١٠٠٪ بيانات موثقة',
    refresh: 'تحديث',

    // Goal Names
    'Steps Goal': 'هدف الخطوات',
    'Water Intake': 'شرب الماء',
    'Calories Burned': 'حرق السعرات',

    // Weekdays
    'Mon': 'إثنين', 'Tue': 'ثلاثاء', 'Wed': 'أربعاء', 'Thu': 'خميس', 'Fri': 'جمعة', 'Sat': 'سبت', 'Sun': 'أحد',

    // Home Vitals & Moods
    feelingAmazing: 'رائع',
    feelingHappy: 'سعيد',
    feelingNeutral: 'طبيعي',
    feelingSad: 'حزين',
    feelingWorried: 'قلق',
    excellent: 'ممتاز',
    great: 'رائع',
    good: 'جيد',
    excellentHealth: 'صحة ممتازة',
    goodHealth: 'بصحة جيدة',
    onTrack: 'ضمن المسار',
    improving: 'في تحسن',
    heartRate: 'ضربات القلب',
    stepCount: 'الخطوات',
    dailySteps: 'الخطوات اليومية',
    sleep: 'النوم',
    hours: 'ساعة',
    hydration: 'الترطيب',
    bpm: 'نبضة/دقيقة',

    // Quick Actions Categories & Items
    qaHeader: 'إجراءات سريعة',
    qaSub: 'الوصول إلى جميع الميزات في مكان واحد',
    mgmt: 'إدارة الصحة',
    homeDash: 'لوحة التحكم الرئيسية',
    homeDashSub: 'نظرة عامة على صحتك اليومية',
    quest: 'استبانة الصحة',
    questSub: 'أكمل ملفك الصحي',
    myProfile: 'ملفي الصحي',
    myProfileSub: 'هوية صحية مخصصة لك',
    medTrack: 'متتبع الأدوية',
    medTrackSub: 'تتبع الأدوية والجداول الزمنية',
    healthAI: 'مساعد الصحة الذكي',
    healthAISub: 'تحدث مع بوت الصحة الذكي',
    wellness: 'العافية ونمط الحياة',
    wellnessSub: 'تتبع صحتك اليومية',
    familyMon: 'العائلة والمراقبة',
    familyDash: 'لوحة التحكم العائلية',
    familyDashSub: 'مراقبة العلامات الحيوية للعائلة',
    addMember: 'إضافة فرد للعائلة',
    addMemberSub: 'تسجيل أفراد جدد للعائلة',
    emergSupp: 'الطوارئ والدعم',
    emergServ: 'خدمات الطوارئ',
    emergServSub: 'وصول سريع للمساعدة الطارئة',
    bloodNet: 'شبكة التبرع بالدم',
    bloodNetSub: 'تبرع بالدم وأنقذ الأرواح',
    medCare: 'الرعاية الطبية',
    browseDocs: 'تصفح الأطباء',
    browseDocsSub: 'البحث وحجز المواعيد',
    myDocs: 'أطبائي',
    myDocsSub: 'عرض الأطباء المحفوظين والسجل',
    medReports: 'التقارير الطبية',
    medReportsSub: 'الوصول لجميع التقارير الطبية',
    manageApps: 'إدارة مواعيدك',
    syncDevCat: 'الأجهزة والمزامنة',
    syncDev: 'توصيل الأجهزة',
    syncDevSub: 'مزامنة أجهزة الصحة الذكية',
    devDash: 'لوحة تحكم الأجهزة',
    devDashSub: 'بيانات الاستشعار الشخصية',
    prefSet: 'الإعدادات والتفضيلات',
    allSettings: 'جميع الإعدادات',
    allSettingsSub: 'إدارة تفضيلات التطبيق',
    personalDetails: 'التفاصيل الشخصية',
    personalDetailsSub: 'تحديث معلوماتك',
    security: 'الأمان',
    securitySub: 'إدارة إعدادات الأمان',
    privacy: 'الخصوصية',
    privacySub: 'التحكم في خصوصيتك',
    notifications: 'التنبيهات',
    notificationsSub: 'تخصيص تنبيهات التطبيق',
    accessibility: 'سهولة الوصول',
    accessibilitySub: 'خيارات سهولة الوصول',
    healthPref: 'التفضيلات الصحية',
    healthPrefSub: 'تحديد الأهداف والتفضيلات',
    medRec: 'السجلات الطبية',
    medRecSub: 'إدارة السجلات الطبية',

    // Wellness Hub
    wellnessHub: 'مركز العافية',
    wellnessSub: 'تتبع صحتك اليومية ونمط حياتك',
    todayProgress: 'تقدم اليوم',
    wellnessCats: 'فئات العافية',
    calories: 'السعرات الحرارية',
    nutrition: 'التغذية',
    nutritionSub: 'تتبع الوجبات والسعرات الحرارية',
    exercise: 'التمرين',
    exerciseSub: 'تسجيل التمارين والنشاط',
    mindfulness: 'اليقظة الذهنية',
    mindfulnessSub: 'التأمل والتنفس',
    goalsSub: 'تحديد وتتبع أهداف العافية',
    mealsToday: '٣ وجبات اليوم',
    exerciseTime: '٤٥ دقيقة اليوم',
    breathTime: '١٠ دقائق اليوم',
    activeGoals: '٤ أهداف نشطة',
    recentAchieve: 'الإنجازات الأخيرة',
    waterChampion: 'بطل الترطيب',
    earlyBird: 'الطائر المبكر',
    dailyWellnessTip: 'نصيحة العافية اليومية',
    hydrationTipLong: 'حافظ على رطوبتك! استهدف شرب ٨ أكواب من الماء طوال اليوم. يؤدي جسمك أداءً أفضل عندما يكون رطباً بشكل صحيح.',

    // Water Intake
    waterIntakeTitle: 'شرب الماء',
    waterIntakeSub: 'تتبع الترطيب',
    ofGlasses: '{x} من {y} أكواب',
    quickAdd: 'إضافة سريعة',
    small: 'صغير',
    glass: 'كوب',
    bottle: 'زجاجة',
    large: 'كبير',
    customAmount: 'كمية مخصصة',
    tapAdjust: 'اضغط +/- للتعديل',
    todayLog: 'سجل اليوم',
    weeklyProgress: 'التقدم الأسبوعي',
    avgDaily: 'المتوسط اليومي',
    daysGoalMet: 'أيام تحقيق الهدف',
    successRate: 'نسبة النجاح',
    hydrationTip: 'نصيحة الترطيب',
    hydrationTipMsg: 'شرب الماء قبل النوم يحسن جودة النوم بشكل ملحوظ.',

    // Steps
    stepsTrackerTitle: 'عداد الخطوات',
    stepsTrackerSub: 'مراقبة النشاط',
    goalLabel: 'الهدف:',
    activeNow: 'نشط الآن',
    minUnit: 'د',
    active: 'نشط',
    distLabel: 'مسافة',
    tripsLabel: 'رحلات',
    weeklyActivity: 'النشاط الأسبوعي',
    movementHistory: 'سجل الحركة',
    viewMap: 'عرض الخريطة',
    morningWalk: 'مشية الصباح',
    afternoonTrip: 'رحلة المساء',
    healthType: 'صحة',
    travelType: 'سفر',
    topWalker: 'أفضل ماشٍ',
    peakEnergy: 'طاقة قصوى',
    setDailyGoal: 'تحديد هدف يومي',
    targetSteps: 'الخطوات المستهدفة',
    stepsGoalHint: 'استهداف 10,000 خطوة رائع لصحة القلب.',
    updateGoal: 'تحديث الهدف',
    cancel: 'إلغاء',

    // Nutrition
    nutritionTitle: 'التغذية',
    todayCalories: 'سعرات اليوم',
    of: 'من',
    kcal: 'سعرة',
    remaining: 'متبقي',
    kcalLeft: 'سعرة متبقية',
    macronutrients: 'العناصر الغذائية',
    protein: 'بروتين',
    carbs: 'كربوهيدرات',
    fats: 'دهون',
    todayMeals: 'وجبات اليوم',
    snack: 'وجبة خفيفة',
    drink: 'مشروب',
    dessert: 'حلوى',
    weeklyCalories: 'السعرات الأسبوعية',
    avgDailyIntake: 'متوسط الاستهلاك اليومي',
    nutritionTip: 'نصيحة التغذية',
    nutritionTipMsg: 'وجبات الإفطار الغنية بالبروتين تبقيك شبعانًا لفترة أطول.',

    // Sleep 
    sleepTrackerTitle: 'تتبع النوم',
    sleepTrackerSub: 'مراقبة الراحة والجودة',
    lastNightSleep: 'نوم الليلة الماضية',
    hoursUnit: 'س',
    bedtime: 'وقت النوم',
    wakeUp: 'وقت الاستيقاظ',
    sleepStages: 'مراحل النوم',
    awake: 'مستيقظ',
    rem: 'حركة العين السريعة',
    lightSleep: 'خفيف',
    deepSleep: 'عميق',
    sleepMetrics: 'مقاييس النوم',
    sleepScore: 'درجة النوم',
    avgHeartRate: 'متوسط نبض القلب',
    restfulness: 'الهدوء',
    weeklySleep: 'النوم الأسبوعي',
    avgSleep: 'متوسط النوم',
    avgQuality: 'متوسط الجودة',
    goalDays: 'أيام الهدف',
    sleepBetter: 'نوم أفضل',
    tipSleepSchedule: 'حافظ على جدول نوم ثابت',
    tipAvoidScreens: 'تجنب الشاشات قبل النوم',
    tipCoolRoom: 'حافظ على برودة الغرفة',
    tipLimitCaffeine: 'قلل من الكافيين',
    setSleepSchedule: 'ضبط جدول النوم',

    // Mindfulness 
    mindfulnessTitle: 'اليقظة الذهنية',
    breathControl: 'التحكم في التنفس',
    incBreathQuality: 'تحسين جودة التنفس',
    startBreathing: 'ابدأ التنفس',
    dailyMeditations: 'التأملات اليومية',
    stressRelief: 'تخفيف التوتر',
    focusSession: 'جلسة تركيز',
    dailyStreak: 'الاستمرارية اليومية',

    // Health AI
    aiGreeting: "مرحباً! أنا مساعدك الصحي الذكي. أنا هنا لمساعدتك في الاستفسارات المتعلقة بالنظام الغذائي والتغذية واللياقة البدنية والعافية والصحة العامة. كيف يمكنني مساعدتك اليوم؟",
    quickQsLabel: 'أسئلة سريعة:',
    q1: 'ماذا يجب أن آكل في الفطور؟',
    q2: 'كم عدد السعرات التي يجب تناولها؟',
    q3: 'كم كمية الماء التي أحتاجها يومياً؟',
    q4: 'كيف يمكنني تحسين صحة قلبي؟',
    q5: 'أطعمة تعزز وظائف الدماغ؟',
    q6: 'نصائح لنوم أفضل؟',
    aiPlaceholder: 'اسألني عن صحتك...',
    aiResponseMock: "هذا سؤال رائع! بناءً على ملفك الصحي، أنصحك بالتركيز على الوجبات الغنية بالبروتين والحفاظ على ترطيب دائم. هل تريد خطة مفصلة؟",

    // Medicine Tracker
    medTitle: 'متتبع الأدوية',
    medSubtitle: 'ابق على اطلاع بمواعيد أدويتك',
    taken: 'تم التناول',
    missed: 'فائت',
    upcoming: 'قادم',
    yourMeds: 'أدويتك',
    nextDose: 'الجرعة القادمة',
    supply: 'المخزون',
    twiceDaily: 'مرتين يومياً',
    onceDaily: 'مرة واحدة يومياً',
    threeTimesDaily: 'ثلاث مرات يومياً',
    takenToday: 'تم التناول اليوم',
    tomorrow: 'غداً',

    // Reports
    reportsTitle: 'التقارير الطبية',
    searchReports: 'البحث في التقارير...',
    total: 'المجموع',
    diag: 'التشخيص',
    shareReport: 'مشاركة التقرير الطبي',
    view: 'عرض',
    download: 'تحميل',
    share: 'مشاركة',

    // Report Types & Diagnoses
    reportCardiology: 'تقرير القلب',
    reportPhysical: 'الفحص البدني',
    reportLab: 'نتائج المختبر',
    reportNeurology: 'تقرير الأعصاب',
    reportOrthopedic: 'تقرير العظام',
    reportDental: 'تقرير الأسنان',
    reportEye: 'فحص العين',
    reportDermatology: 'تقرير الجلدية',
    diagHypertension: 'ارتفاع طفيف في الضغط',
    diagHealthy: 'صحة ممتازة',
    diagCholesterol: 'ارتفاع الكوليسترول',
    diagNeurological: 'أعصاب طبيعية',
    diagOrthopedic: 'انحراف طفيف في العمود الفقري',
    diagDental: 'تنظيف دوري',
    diagVision: 'تصحيح رؤية',
    diagSkin: 'فحص إكزيما',
    attention: 'يحتاج انتباه',
    total: 'المجموع',
    complete: 'مكتمل',
    diag: 'التشخيص',
    reportPreview: 'معاينة التقرير',
    searchInReport: 'بحث في التقرير...',
    generalCheckupReport: 'تقرير فحص عام',
    patientDetails: 'تفاصيل المريض',
    vitals: 'العلامات الحيوية',
    docObservations: 'ملاحظات الطبيب',
    notesNextSteps: 'الملاحظات والخطوات التالية',
    name: 'الاسم',
    dob: 'تاريخ الميلاد',
    gender: 'الجنس',
    age: 'العمر',
    me: 'أنا',
    selectDate: 'اختر التاريخ',
    camera: 'كاميرا',

    // Lifestyle & DNA
    smoking: 'التدخين',
    alcoholLevel: 'مستوى الكحول',
    dnaSampleType: 'نوع عينة الـ DNA',
    activityLevel: 'مستوى النشاط',
    dietType: 'نوع الحمية',
    sleepDuration: 'مدة النوم',

    // Detailed Vitals (Reports)
    bloodPressureLabel: 'ضغط الدم',
    pulseLabel: 'النبض',
    tempLabel: 'درجة الحرارة',
    respiratoryRate: 'معدل التنفس',
    bpm: 'نبضة/دقيقة',
    weight: 'الوزن',
    height: 'الطول',

    // Appointments & Reminders
    activeReminders: 'تنبيهات نشطة',
    myMedicine: 'أدويتي',
    upcomingReminders: 'التنبيهات القادمة',
    inXHours: 'خلال {x} ساعات',
    quickStats: 'إحصائيات سريعة',
    reminders: 'التذكيرات',
    deleteReminderTitle: 'حذف التذكير؟',
    deleteReminderMsg: 'هل أنت متأكد أنك تريد حذف هذا التذكير؟',
    deleteNow: 'حذف الآن',
    asPrescribed: 'حسب الوصفة',
    all: 'الكل',

    // Share
    copyLinkDesc: 'انسخ الرابط أو شارك عبر وسائل التواصل الاجتماعي',
    copied: 'تم النسخ',
    copy: 'نسخ',
    more: 'المزيد',
    whatsapp: 'واتساب',
    telegram: 'تليجرام',
    email: 'البريد الإلكتروني',

    // Family Hub
    dataSharingAgreem: 'اتفاقية مشاركة البيانات',
    familyDataSub: 'معلومات هامة حول بيانات صحة العائلة',
    fullVis: 'رؤية كاملة للبيانات',
    fullVisSub: 'سيكون لجميع أفراد العائلة الذين تضيفهم حق الوصول لعرض المعلومات الصحية الكاملة لبعضهم البعض، بما في ذلك السجلات الطبية والعلامات الحيوية والأدوية والتقارير.',
    sharedDash: 'لوحة تحكم صحية مشتركة',
    sharedDashSub: 'سيظهر كل عضو في لوحة تحكم صحة العائلة الخاصة بك، وسيتم مراقبة بياناتهم الصحية وعرضها باستمرار.',
    consentReq: 'الموافقة مطلوبة',
    consentReqSub: 'بإضافة فرد من العائلة، فإنك تؤكد أن لديك موافقتهم على مشاركة معلوماتهم الصحية على هذه المنصة.',
    iAgreeTerms: 'أفهم وأوافق على أن جميع أفراد العائلة سيكون لهم حق الوصول لعرض البيانات الصحية الكاملة لبعضهم البعض، وقد حصلت على موافقة الشخص الذي أضيفه.',
    agreeCont: 'أوافق، متابعة',
    memberDetails: 'تفاصيل العضو',
    age: 'العمر',
    gender: 'الجنس',
    relationship: 'العلاقة',
    inviteSent: 'تم إرسال الدعوة',
    online: 'متصل',
    offline: 'غير متصل',
    typeMessage: 'اكتب رسالة...',
    familyHubChat: 'دردشة ملتقى العائلة',
    searchFamily: 'البحث عن أفراد العائلة...',
    familyGroup: 'مجموعة العائلة',
    previewAR: 'استكشاف الواقع المعزز',
    welcomeAR: 'مرحباً بكم في تجربة سنيكد للواقع المعزز',
    viewInSpace: 'عرض في مساحتك',
    groupChatSub: 'تحدث مع الجميع في وقت واحد',
    privateMessages: 'الرسائل الخاصة',
    participants: 'مشاركين',
    videoCallInc: 'مكالمة فيديو واردة...',
    endCall: 'إنهاء المكالمة',
    chatSysMsg: 'بدأت دردشة العائلة. كن لطيفاً!',
    chatAutoReply: 'شكراً على رسالتك! أنا مشغول الآن وسأرد عليك قريباً.',
    healthy: 'بصحة جيدة',
    yearsOld: 'سنة',
    managePrivacy: 'إدارة مشاركة البيانات والخصوصية',
    live: 'مباشر',
    bpm: 'نبضة/دقيقة',
    good: 'جيد',
    todayMood: 'المزاج اليوم',
    allergies: 'الحساسية',
    healthId: 'الهوية الصحية',
    historyTitle: 'السجل',
    insurance: 'التأمين',
    medicalHist: 'السجل الطبي',
    files: 'ملفات',
    daily: 'يومياً',
    uploadNewReport: 'رفع تقرير جديد',
    privacySharing: 'الخصوصية والمشاركة',
    privacyDesc: 'تحكم في البيانات الصحية التي يمكن لهذا العضو رؤيتها في ملفك الشخصي.',
    overallSharing: 'مستوى المشاركة العام',
    familyOnly: 'أفراد العائلة فقط',
    emergDocs: 'الطوارئ والأطباء',
    fullAccess: 'وصول كامل',
    noAccess: 'عدم الوصول',
    youPoked: 'لقد نبهت',
    pokeNote: 'سيتلقون تنبيهاً قريباً.',
    privacyUpdated: 'تم تحديث تفضيلات الخصوصية!',

    // Emergency Relations & Info
    relWife: 'الزوجة',
    relBrother: 'الأخ',
    relDoctor: 'الطبيب المعالج',
    emergencyTitle: 'الطوارئ',
    emergencySubtitle: 'وصول سريع لخدمات الطوارئ',
    medicalAlerts: 'تنبيهات طبية',
    criticalInfo: 'معلومات حرجة',
    bloodType: 'فصيلة الدم',
    dnaType: 'نوع الـ DNA',
    age: 'العمر',
    weight: 'الوزن',
    yearsOld: 'سنة',
    kg: 'كجم',
    allergies: 'الحساسية',
    currentMedications: 'الأدوية الحالية',
    emergencyContacts: 'جهات اتصال الطوارئ',
    nearbyHospitals: 'المستشفيات القريبة',
    er: 'طوارئ',
    callAction: 'اتصال',
    directionsAction: 'الاتجاهات',

    // Doctors & Specialties
    findDoctors: 'ابحث عن طبيب',
    bookSpecialists: 'حجز مواعيد أخصائيين',
    searchDoctorsSpec: 'ابحث عن أطباء، تخصصات...',
    allSpecialties: 'جميع التخصصات',
    viewMyDoctors: 'عرض أطبائي',
    availableToday: 'متاح اليوم',
    availableTomorrow: 'متاح غداً',
    nextDoseTime: 'القادم',
    cardiology: 'القلب',
    neurology: 'الأعصاب',
    orthopedics: 'العظام',
    general: 'عام',
    addFamilyMember: 'إضافة فرد للعائلة',
    enterHealthInfo: 'أدخل معلوماتهم الصحية',
    fullNameLabel: 'الاسم الكامل',
    enterFullName: 'أدخل الاسم الكامل',
    selectRelationship: 'اختر العلاقة',
    dobLabel: 'تاريخ الميلاد',
    genderLabel: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    other: 'آخر',
    phoneNum: 'رقم الهاتف',
    bloodType: 'فصيلة الدم',
    selectBloodType: 'اختر فصيلة الدم',
    knownAllergies: 'حساسية معروفة',
    listAllergies: 'قائمة بأي نوع من الحساسية',
    saveFinish: 'حفظ وإنهاء',
    fillRequired: 'يرجى ملء جميع الحقول المطلوبة',
    relationships: {
      Father: 'الأب',
      Mother: 'الأم',
      Son: 'الابن',
      Daughter: 'الابنة',
      Grandfather: 'الجد',
      Grandmother: 'الجدة',
      Brother: 'الأخ',
      Sister: 'الأخت',
      Other: 'آخر'
    },
    chooseAvatar: 'اختر الرمز التعبيري',
    selectProfilePic: 'اختر صورة ملف شخصي لك',
    avatarList: {
      Man: 'رجل',
      Woman: 'امرأة',
      Boy: 'ولد',
      Girl: 'بنت',
      'Elderly Man': 'رجل مسن',
      'Elderly Woman': 'امرأة مسنة',
      Baby: 'طفل رضيع',
      Person: 'شخص',
      Doctor: 'طبيب',
      Nurse: 'ممرضة',
      Child: 'طفل',
      Elder: 'كبير في السن'
    },
    familyAch: 'إنجازات العائلة',
    stepChart: 'مخطط الخطوات الأسبوعي',
    goalSteps: 'الهدف: 10 آلاف خطوة',
    achBadges: 'الإنجازات والأوسمة',
    tenKClub: 'نادي الـ 10 آلاف',
    workouts: 'تمارين',
    congratulate: 'تهنئة',
    sent: 'تم الإرسال',
    congratsSentTo: 'تم إرسال التهنئة إلى',
    logIn: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    letsGetStarted: 'لنبدأ معاً',
    emailAddress: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    eightChars: '8+ أحرف',
    numbers: 'أرقام',
    symbols: 'رموز',
    forgetPassQ: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    signUpAction: 'إنشاء حساب',
    pleaseEnterEmail: 'يرجى إدخال البريد الإلكتروني للمتابعة',
    pleaseEnterPassword: 'يرجى إدخال كلمة المرور',
    skip: 'تخطي',
    createAccount: 'إنشاء حساب جديد',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    termsService: 'شروط الخدمة',
    privacyPolicyAuth: 'سياسة الخصوصية',
    pleaseSignUp: 'يرجى إنشاء حساب لتسجيل الدخول',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    firstNameRequired: 'الاسم الأول مطلوب',
    lastNameRequired: 'اسم العائلة مطلوب',
    invalidEmail: 'عنوان البريد الإلكتروني غير صالح',
    minEightChars: 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    emailExists: 'البريد الإلكتروني موجود بالفعل',
    forgetPassTitle: 'نسيت كلمة المرور؟',
    enterVerifCode: 'أدخل رمز التحقق',
    sentToEmail: 'المرسل إلى بريدك الإلكتروني',
    resetPass: 'إعادة تعيين كلمة المرور',
    newPassword: 'كلمة مرور جديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    passNotMatch: 'كلمات المرور لا تتطابق أو قصيرة جداً',
    rememberedPass: 'تذكرت كلمة المرور الخاصة بي.',
    confirmationTitle: 'التأكيد',
    enterCodeSentTo: 'أدخل الكود المرسل إلى',
    incorrectCode: 'الكود غير صحيح. يرجى المحاولة مرة أخرى.',
    didntReceiveCode: 'لم تستلم الكود؟',
    resendCode: 'إعادة إرسال الكود',
    verify: 'تحقق',
    confirmedTitle: 'تم التأكيد',
    phoneVerified: 'تم التحقق من رقم هاتفك بنجاح.',
    getStarted: 'ابدأ الآن',
    registrationTitle: 'التسجيل',
    enterPhoneVerify: 'أدخل رقم هاتفك للتحقق من حسابك.',
    phoneNumberPlaceholder: 'رقم الهاتف',
    continue: 'استمرار',
    countries: {
      Egypt: 'مصر',
      Saudi: 'السعودية',
      UAE: 'الإمارات'
    },
    welcomeTitle: 'مرحباً بك في سنيكد (SYNCED)',
    welcomeDesc: 'منظومتك الشاملة للصحة والعافية. كل ما تحتاجه، مجمع في منصة ذكية واحدة.',
    trackTitle: 'التتبع والمراقبة',
    trackDesc: 'سجل أدويتك، وراقب علاماتك الحيوية اليومية، واحتفظ بجميع سجلاتك الطبية بأمان في جيبك.',
    aiTitle: 'مساعد الصحة بالذكاء الاصطناعي',
    aiDesc: 'دردش مع ذكائنا الاصطناعي الذكي لتحليل الأعراض فوراً والتواصل بسلاسة مع أفضل المهنيين الطبيين.',
    familyTitle: 'العائلة والطوارئ',
    familyDesc: 'اربط أحباءك بمركز عائلي مشترك، واحصل على وصول فوري لدعم الطوارئ بضغطة واحدة.',
    loginOrRegister: 'تسجيل الدخول أو إنشاء حساب',
    orLabel: 'أو',
    skipToQuiz: 'تخطي إلى الاختبار الافتراضي',
    basicInfoTitle: 'معلومات أساسية',
    enterMedNameDosage: 'أدخل اسم الدواء والجرعة',
    medBoxPhoto: 'صورة علبة الدواء',
    takeBoxPhoto: 'التقط صورة للعلبة',
    helpsIdentify: 'يساعد في التعرف على الدواء بشكل صحيح',
    retake: 'إعادة الالتقاط',
    captured: 'تم الالتقاط',
    medName: 'اسم الدواء',
    aspirinEx: 'مثال: أسبرين',
    doseAmount: 'كمية الجرعة',
    unit: 'الوحدة',
    colorTheme: 'نسق الألوان',
    camError: 'تعذر الوصول إلى الكاميرا. يرجى التحقق من الأذونات.',
    dosageScheduleTitle: 'الجرعة والجدول الزمني',
    setFreqTiming: 'حدد التكرار والموعد',
    frequencyLabel: 'التكرار',
    timeSlots: 'فترات زمنية',
    durationDays: 'مدة العلاج (أيام)',
    frequencyOptions: {
      'Once daily': 'مرة يومياً',
      'Twice daily': 'مرتين يومياً',
      'Three times daily': 'ثلاث مرات يومياً',
      'Four times daily': 'أربع مرات يومياً',
      'Custom schedule': 'جدول مخصص'
    },
    remindersTitle: 'التذكيرات',
    configNotifs: 'ضبط الإشعارات',
    enableReminders: 'تفعيل التذكيرات',
    getNotifiedTime: 'احصل على إشعار في الوقت المحدد',
    willRecieveRemindersAt: 'سوف تتلقى تذكيرات في:',
    additionalDetailsTitle: 'تفاصيل إضافية',
    finalCustomization: 'التخصيص النهائي',
    notesOptional: 'ملاحظات (اختياري)',
    notesPlaceholder: 'مثال: يؤخذ مع الطعام، تجنب الكحول...',
    summary: 'الملخص',
    schedule: 'الجدول الزمني',
    duration: 'المدة',
    addMedicineAction: 'إضافة دواء',
    enabled: 'مفعل',
    disabled: 'معطل',

    // Settings & Accessibility
    settings: 'الإعدادات',
    manageAccount: 'إدارة الحساب',
    profile: 'الملف الشخصي',
    securityDetails: 'تفاصيل الأمان',
    accessibility: 'إمكانية الوصول',
    healthAndMedical: 'الصحة والطب',
    healthPreferences: 'تفضيلات الصحة',
    medicalRecords: 'السجلات الطبية',
    appointmentSettings: 'إعدادات المواعيد',
    deviceConnectivity: 'الجهاز والاتصال',
    connectedDevices: 'الأجهزة المتصلة',
    notifications: 'الإشعارات',
    notificationSettings: 'إعدادات الإشعارات',
    legalPrivacy: 'القانون والخصوصية',
    privacySettings: 'إعدادات الخصوصية',
    helpCenter: 'مركز المساعدة',
    languageSelector: 'محدد اللغة',
    appLanguage: 'لغة التطبيق',
    appearance: 'المظهر',
    theme: 'العلامة التجارية',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    textSize: 'حجم النص',
    fontSize: 'حجم الخط',
    sizeHint: 'هكذا سيظهر النص الخاص بك في جميع أنحاء التطبيق.',
    visualAdjustments: 'التعديلات المرئية',
    highContrast: 'تباين عالي',
    highContrastDesc: 'زيادة تباين الألوان',
    reduceMotion: 'تقليل الحركة',
    reduceMotionDesc: 'تقليل الرسوم المتحركة',
    colorAccessibility: 'سهولة الوصول للألوان',
    colorBlindMode: 'وضع عمى الألوان',
    pointerCursor: 'المؤشر والمؤشر',
    cursorSize: 'حجم المؤشر',
    audioSpeech: 'الصوت والكلام',
    resetToDefault: 'إعادة التعيين إلى الإعدادات الافتراضية',
    accessibilityDisclaimer: 'تساعد هذه الإعدادات في جعل التطبيق أكثر سهولة في الوصول وأسهل في الاستخدام للجميع.',

    // Personal/Edit Profile
    personalInformation: 'معلومات شخصية',
    editProfile: 'تعديل الملف الشخصي',
    accountSettings: 'إعدادات الحساب',
    healthIdCard: 'بطاقة الهوية الصحية',
    shareProfile: 'مشاركة الملف الشخصي',
    downloadHealthData: 'تحميل البيانات الصحية',
    verifiedAccount: 'حساب موثق',
    quickActions: 'إجراءات سريعة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    dob: 'تاريخ الميلاد',
    location: 'الموقع',
    healthInformation: 'معلومات صحية',
    bloodType: 'فصيلة الدم',
    weight: 'الوزن',
    height: 'الطول',
    bmi: 'مؤشر كتلة الجسم',
    allergies: 'الحساسية',
    medicalConditions: 'الحالات الطبية',
    emergencyContact: 'جهة اتصال الطوارئ',
    contactName: 'اسم جهة الاتصال',
    relationship: 'العلاقة',
    phoneNumber: 'رقم الهاتف',
    save: 'حفظ',
    tapToChange: 'انقر لتغيير الصورة',

    // Security Details
    securityDetailsTitle: 'تفاصيل الأمان',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    updatePasswordAction: 'تحديث كلمة المرور',
    twoFactorAuth: 'المصادقة الثنائية',
    smsAuth: 'المصادقة عبر SMS',
    smsAuthDesc: 'تلقي الرموز عبر رسالة نصية',
    emailAuth: 'المصادقة عبر البريد الإلكتروني',
    emailAuthDesc: 'تلقي الرموز عبر البريد الإلكتروني',
    authApp: 'تطبيق المصادقة',
    authAppDesc: 'استخدم تطبيق المصادقة',
    biometricSecurity: 'الأمان الحيوي',
    faceId: 'بصمة الوجه',
    faceIdDesc: 'استخدم التعرف على الوجه لإلغاء القفل',
    fingerprint: 'بصمة الإصبع',
    fingerprintDesc: 'استخدم بصمة الإصبع لإلغاء القفل',
    loginActivity: 'نشاط تسجيل الدخول',
    activeStatus: 'نشط',
    removeAction: 'إزالة',

    // Health Preferences
    healthPreferencesTitle: 'تفضيلات الصحة',
    healthGoals: 'الأهداف الصحية',
    weightManagement: 'إدارة الوزن',
    weightManagementDesc: 'تتبع الوزن وتحديد الأهداف',
    fitnessTracking: 'تتبع اللياقة البدنية',
    fitnessTrackingDesc: 'مراقبة النشاط اليومي',
    sleepQuality: 'جودة النوم',
    sleepQualityDesc: 'تتبع أنماط النوم',
    vitalSignsTargets: 'أهداف العلامات الحيوية',
    targetHeartRate: 'معدل ضربات القلب المستهدف (نبضة في الدقيقة)',
    bloodPressure: 'ضغط الدم (ملم زئبق)',
    dailyStepsGoal: 'هدف الخطوات اليومية',
    waterIntakeGoal: 'هدف شرب الماء (لتر)',
    nutritionPreferences: 'تفضيلات التغذية',
    dietaryRestrictions: 'القيود الغذائية',
    calorieTracking: 'تتبع السعرات الحرارية',
    calorieTrackingDesc: 'مراقبة السعرات الحرارية اليومية',
    mealReminders: 'تذكيرات الوجبات',
    mealRemindersDesc: 'الحصول على تذكيرات للوجبات',
    savePreferencesAction: 'حفظ التفضيلات',

    // Medical Records
    medicalRecordsTitle: 'السجلات الطبية',
    addRecord: 'إضافة سجل',
    searchDocuments: 'البحث في المستندات...',
    uploadMedicalRecords: 'تحميل السجلات الطبية',
    uploadLimit: 'PDF، JPEG، PNG حتى 10 ميجابايت',
    chooseFiles: 'اختار الملفات',
    recentRecords: 'السجلات الأخيرة',
    verified: 'موثق',
    viewAction: 'عرض',
    downloadAction: 'تحميل',
    shareAction: 'مشاركة',
    browseByCategory: 'تصفح حسب الفئة',
    filesCount: 'ملفات',
    noRecordsFound: 'لم يتم العثور على سجلات تطابق بحثك',
    allRecords: 'كل السجلات',
    labResults: 'نتائج المختبر',
    imaging: 'التصوير الطبي',
    prescriptions: 'الوصفات الطبية',
    immunizations: 'التطعيمات',
    exams: 'الفحوصات',

    // Appointment Settings
    appointmentSettingsTitle: 'إعدادات المواعيد',
    apptPreferences: 'التفضيلات',
    defaultApptType: 'نوع الموعد الافتراضي',
    inPersonVisits: 'زيارات شخصية',
    preferredTimeSlot: 'الفتحة الزمنية المفضلة',
    morningTime: 'الصباح (9 صباحًا - 12 مساءً)',
    autoConfirmAppts: 'تأكيد المواعيد تلقائيًا',
    skipConfirmation: 'تخطي خطوة التأكيد',
    upcomingAppointments: 'المواعيد القادمة',
    rescheduleAction: 'إعادة جدولة',
    cancelAction: 'إلغاء',
    telemedicine: 'الطب عن بعد',
    appointmentTypes: 'أنواع المواعيد',
    videoConsultations: 'الاستشارات المرئية',
    virtualAppts: 'مواعيد افتراضية',
    phoneConsultations: 'الاستشارات الهاتفية',
    audioOnlyCalls: 'مكالمات صوتية فقط',
    cancellationPolicy: 'سياسة الإلغاء',
    gracePeriod: 'فترة السماح',
    gracePeriodDesc: 'يمكنك إلغاء أو إعادة جدولة المواعيد قبل ما يصل إلى 24 ساعة من الموعد المقرر دون أي رسوم. قد تترتب رسوم على الإلغاء المتأخر.',
    sendCancellationReminders: 'إرسال تذكيرات الإلغاء',
    deadlineDesc: '24 ساعة قبل الموعد النهائي',

    // Connected Devices
    connectedDevicesTitle: 'الأجهزة المتصلة',
    connectNewDevice: 'توصيل جهاز جديد',
    yourDevices: 'أجهزتك',
    connectedStatus: 'متصل',
    inactiveStatus: 'غير نشط',
    lastSyncedText: 'آخر مزامنة',
    autoSyncEnabled: 'تم تمكين المزامنة التلقائية',
    reconnectAction: 'إعادة الاتصال',
    syncSettings: 'إعدادات المزامنة',
    autoSyncAll: 'مزامنة تلقائية لجميع الأجهزة',
    autoSyncDesc: 'المزامنة تلقائيًا عندما تكون في النطاق',
    backgroundSync: 'مزامنة في الخلفية',
    backgroundSyncDesc: 'مزامنة البيانات في الخلفية',
    syncFrequency: 'تردد المزامنة',
    every30Min: 'كل 30 دقيقة',
    wifiOnlySync: 'مزامنة Wi-Fi فقط',
    wifiOnlyDesc: 'المزامنة فقط عندما تكون على Wi-Fi',
    dataPermissions: 'صلاحيات البيانات',
    heartRateData: 'بيانات معدل ضربات القلب',
    allowAccessDesc: 'السماح للتطبيقات بالوصول',
    activityFitness: 'النشاط واللياقة البدنية',
    activityFitnessDesc: 'الخطوات والسعرات الحرارية والتمارين',
    sleepData: 'بيانات النوم',
    sleepDataDesc: 'أنماط وجودة النوم',
    bloodPressureData: 'ضغط الدم',
    bloodPressureDesc: 'قياسات ضغط الدم',
    bloodGlucose: 'جلوكوز الدم',
    bloodGlucoseDesc: 'قراءات مستوى الجلوكوز',

    // Notification Settings
    notificationSettingsTitle: 'إعدادات الإشعارات',
    apptReminders: 'تذكيرات المواعيد',
    apptRemindersDesc: 'الحصول على إشعار قبل المواعيد',
    reminderTiming: 'توقيت التذكير',
    reminderTimingDesc: 'قبل يوم وساعة واحدة',
    apptCancellations: 'إلغاء المواعيد',
    apptCancellationsDesc: 'الإعلام بالتغييرات',
    medReminders: 'تذكيرات الأدوية',
    medRemindersDesc: 'تذكيرك بتناول الأدوية',
    refillReminders: 'تذكيرات إعادة التعبئة',
    refillRemindersDesc: 'تنبيه عند الحاجة لإعادة التعبئة',
    missedDoseAlerts: 'تنبيهات الجرعة الفائتة',
    missedDoseDesc: 'تنبيه في حالة فقدان الجرعة',
    dailyHealthSummary: 'ملخص الصحة اليومي',
    dailyHealthSummaryDesc: 'الحصول على رؤى صحية يومية',
    abnormalReadingsAlert: 'تنبيه قراءات غير طبيعية',
    abnormalReadingsDesc: 'تنبيه للعلامات الحيوية غير العادية',
    goalAchievements: 'تحقيق الأهداف',
    goalAchievementsDesc: 'الاحتفال بإنجازاتك',
    pushNotifications: 'إشعارات الدفع',
    pushNotificationsDesc: 'تلقي إشعارات الدفع',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    emailNotificationsDesc: 'الحصول على التحديثات عبر البريد الإلكتروني',
    smsNotifications: 'إشعارات SMS',
    smsNotificationsDesc: 'تلقي رسائل نصية',
    marketingCommunications: 'اتصالات التسويق',
    marketingCommunicationsDesc: 'نصائح ورؤى صحية',
    quietHours: 'ساعات الهدوء',
    enableQuietHours: 'تمكين ساعات الهدوء',
    quietHoursDesc: 'إسكات الإشعارات غير العاجلة',
    timeRange: 'النطاق الزمني',
    quietHoursRange: '10:00 مساءً - 7:00 صباحاً',

    // Privacy Settings
    privacySettingsTitle: 'إعدادات الخصوصية',
    dataSharing: 'مشاركة البيانات',
    shareWithProviders: 'المشاركة مع مقدمي الرعاية الصحية',
    shareWithProvidersDesc: 'السماح للأطباء بالوصول إلى بياناتك',
    shareWithFamily: 'المشاركة مع أفراد العائلة',
    shareWithFamilyDesc: 'السماح للعائلة بعرض معلوماتك الصحية',
    researchParticipation: 'المشاركة في الأبحاث',
    researchParticipationDesc: 'المساهمة في الأبحاث الصحية',
    anonymousAnalytics: 'تحليلات مجهولة المصدر',
    analyticsDesc: 'ساعد في تحسين خدماتنا',
    visibilityProfile: 'الرؤية والملف الشخصي',
    publicProfile: 'الملف الشخصي العام',
    publicProfileDesc: 'اجعل الملف الشخصي مرئيًا للآخرين',
    showActivityStatus: 'إظهار حالة النشاط',
    activityStatusDesc: 'دع الآخرين يرون متى تكون نشطًا',
    healthAchievements: 'الإنجازات الصحية',
    achievementsDesc: 'عرض إنجازاتك',
    userDataRights: 'حقوق بياناتك',
    downloadYourData: 'تحميل بياناتك',
    downloadDataDesc: 'الحصول على نسخة من جميع معلوماتك',
    exportMedicalRecords: 'تصدير السجلات الطبية',
    exportRecordsDesc: 'تحميل سجلاتك الصحية',
    privacyPolicy: 'سياسة الخصوصية',
    privacyPolicyDesc: 'اقرأ سياسة الخصوصية الخاصة بنا',
    termsOfService: 'شروط الخدمة',
    termsOfServiceDesc: 'مراجعة الشروط والأحكام',
    dataRetention: 'احتفاظ بالبيانات',
    autoDataCleanup: 'تنظيف البيانات التلقائي',
    cleanupDesc: 'سيتم حذف بياناتك تلقائيًا بعد 7 سنوات من عدم النشاط، كما تتطلب قوانين الاحتفاظ بالبيانات الطبية.',
    keepActivityHistory: 'الاحتفاظ بسجل النشاط',
    duration2Years: 'المدة: سنتان',
    dangerZone: 'منطقة الخطر',
    deleteAccount: 'حذف الحساب',
    deleteAccountDesc: 'حذف حسابك وجميع البيانات المرتبطة به نهائيًا. هذا الإجراء لا يمكن التراجع عنه.',
    deleteAccountAction: 'حذف حسابي',

    // Home
    liveHealth: 'الصحة المباشرة',
    feelingToday: 'بماذا تشعر اليوم؟',
    excellent: 'ممتاز',
    great: 'رائع',
    good: 'جيد',
    bpm: 'نبضة/دقيقة',
    tipHydrate: 'حافظ على رطوبة جسمك طوال اليوم',
    tipFruits: 'تناول المزيد من الخضروات الورقية والفواكه',
    overallScore: 'النتيجة الإجمالية',
    profileComplete: 'الملف الشخصي مكتمل',
    verifiedData: 'بيانات موثقة بنسبة 100%',
    healthTips: 'نصائح صحية',
    feelingAmazing: 'رائع',
    feelingHappy: 'سعيد',
    feelingNeutral: 'طبيعي',
    feelingSad: 'حزين',
    feelingWorried: 'قلق',

    // Emergency
    emergencyTitle: 'الطوارئ',
    emergencySubtitle: 'وصول سريع لخدمات الطوارئ',
    medicalAlerts: 'التنبيهات الطبية',
    criticalInfo: 'معلومات هامة',
    bloodType: 'فصيلة الدم',
    dnaType: 'نوع الحمض النووي',
    allergies: 'الحساسية',
    currentMedications: 'الأدوية الحالية',
    emergencyContacts: 'جهات اتصال الطوارئ',
    nearbyHospitals: 'المستشفيات القريبة',
    er: 'الطوارئ',
    callAction: 'اتصال',
    directionsAction: 'الاتجاهات',
    yearsOld: 'سنة',
    kg: 'كجم',
    relWife: 'الزوجة',
    relBrother: 'الأخ',
    relDoctor: 'الطبيب المعالج',

    // Family Hub
    familyHubTitle: 'مركز صحة العائلة',
    familyMembers: 'أفراد العائلة',
    remindersCount: 'تذكيرات',
    upcomingCount: 'قادم',
    familyChat: 'دردشة العائلة',
    excellentHealth: 'صحة ممتازة',
    wellnessScoreFull: 'نتيجة عافية العائلة والإنجازات',
    removeMemberTitle: 'إزالة العضو؟',
    removeMemberConfirm: 'هل أنت متأكد أنك تريد إزالة هذا العضو؟ سيؤدي هذا الإجراء إلى حذف سجلاته الصحية نهائيًا.',
    weeklyBadges: 'شارات أسبوعية',
    newMessagesCount: 'جديد',
    medications: 'الأدوية',
    remove: 'إزالة',

    // Health ID
    verified: 'موثق',
    healthIdSubtitle: 'الهوية الصحية • عضو موثق',
    overallHealthScore: 'درجة الصحة العامة',
    excellentProgress: 'تقدم ممتاز',
    basicInfo: 'المعلومات الأساسية',
    currentVitals: 'العلامات الحيوية الحالية',
    physicalStats: 'الإحصائيات البدنية',
    lifestyleHabits: 'عادات نمط الحياة',
    emergencyPriorityInfo: 'معلومات أولوية الطوارئ',
    chronicConditions: 'الأمراض المزمنة',
    pastSurgeries: 'العمليات الجراحية السابقة',
    geneticsDna: 'الوراثة والحمض النووي',
    geneticRiskFactors: 'عوامل الخطر الجينية',
    familyMedicalHistory: 'التاريخ الطبي للعائلة',
    medicalReportsFiles: 'التقارير الطبية والملفات',
    viewAllReports: 'عرض جميع التقارير',

    // Doctors
    findDoctors: 'ابحث عن أطباء',
    bookSpecialists: 'احجز مواعيد مع المتخصصين',
    searchDoctorsSpec: 'ابحث عن الأطباء، التخصصات...',
    allSpecialties: 'جميع التخصصات',
    viewMyDoctors: 'عرض أطبائي',
    availableToday: 'متاح اليوم',
    availableTomorrow: 'متاح غداً',
    nextDoseTime: 'القادم',
    myDoctorsTitle: 'أطبائي',
    lastVisit: 'آخر زيارة',
    nextAppointment: 'الموعد القادم',
    notScheduled: 'غير مقرر',
    chat: 'دردشة',
    book: 'حجز',
    emergencyServices: 'خدمات الطوارئ',
    poisonControl: 'مركز السموم',
    hospitalHotline: 'الخط الساخن للمستشفى',

    // Blood Network
    bloodNetworkTitle: 'شبكة الدم',
    yourBloodType: 'فصيلة دمك',
    livesImpacted: 'الأرواح المتأثرة',
    nextEligible: 'الموعد القادم المتاح',
    canDonateTo: 'يمكنك التبرع لـ',
    activeRequests: 'نشط',
    criticalRequests: 'حرج',
    nearbyRequests: 'قريب',
    bloodRequestsTitle: 'طلبات الدم',
    nearbyBloodBanks: 'بنوك الدم القريبة',
    donationGuidelines: 'إرشادات التبرع',
    donationGuidelinesDesc: 'يمكنك التبرع بالدم كل 56 يومًا. تأكد من حصولك على قسط كافٍ من الراحة والترطيب وتناول الطعام قبل التبرع.',

    // Devices & Syncing
    syncingData: 'جاري مزامنة البيانات',
    syncSuccess: 'تمت مزامنة جميع البيانات الصحية بنجاح',
    syncWait: 'يرجى الانتظار بينما نجلب بياناتك',
    syncDone: 'تم',
    discoverDevices: 'اكتشاف الأجهزة',
    scanningDevices: 'جاري البحث عن أجهزة قريبة...',
    pairingModeInfo: 'تأكد من تفعيل البلوتوث وأن جهازك في وضع الاقتران',

    // Medical Report Upload
    uploadReportTitle: 'رفع تقرير',
    uploadReportSub: 'أضف الوثائق والتقارير الطبية',
    selectFamilyMember: 'اختر فرد العائلة',
    viewAllMembers: 'عرض جميع الأعضاء',
    reportTitle: 'عنوان التقرير',
    reportTitleExample: 'مثال: نتائج فحص الدم',
    reportDate: 'تاريخ التقرير',
    dropFilesHint: 'أفلت الملفات هنا أو انقر للرفع',
    fileSelected: 'تم اختيار الملف بنجاح',
    uploadLimit: 'PDF، JPG، PNG حتى ١٠ ميجابايت',
    browseFiles: 'تصفح الملفات',
    notesPlaceholderReport: 'أضف أي معلومات إضافية حول هذا التقرير.',
    uploadReportAction: 'رفع التقرير',
    category: 'الفئة',
    imagingLabel: 'التصوير الطبي',
    prescription: 'وصفة طبية',
    checkup: 'فحص',
    vaccination: 'تحصين',

    // QuizHero & Onboarding
    onboardingStep: 'الخطوة {x} من {y}',
    quizSkip: 'تخطي',
    quizBegin: 'لنبدأ',
    quizBack: 'رجوع',
    quizContinue: 'متابعة',
    createHealthIDTitle: 'إنشاء الهوية الصحية',
    createHealthIDDesc: 'لنقم ببناء ملفك الصحي الشخصي في بضع دقائق فقط. بياناتك آمنة وتساعدنا في تقديم رعاية أفضل.',
    personalizedCare: 'رعاية مخصصة',
    personalizedCareSub: 'احصل على توصيات صحية مخصصة',
    emergencyReady: 'جاهز للطوارئ',
    emergencyReadySub: 'معلومات هامة يمكن الوصول إليها عند الحاجة',
    trackProgress: 'تتبع التقدم',
    trackProgressSub: 'راقب رحلتك الصحية مع مرور الوقت',
    tellUsAboutYou: 'أخبرنا عنك',
    basicInfoSub: 'معلومات أساسية للبدء',
    firstName: 'الاسم الأول',
    lastName: 'الكنية',
    firstNamePlaceholder: 'أدخل اسمك الأول',
    lastNamePlaceholder: 'أدخل كنيتك',
    day: 'اليوم',
    month: 'الشهر',
    year: 'السنة',
    physicalStatsTitle: 'الإحصائيات الجسدية',
    metricsSub: 'ساعدنا في تتبع قياساتك الصحية',
    height: 'الطول',
    weight: 'الوزن',
    medicalHistoryTitle: 'السجل الطبي',
    safetyShortSub: 'مهم لسلامتك',
    allergiesPlaceholder: 'مثلاً: البنسلين، الفول السوداني، لا يوجد',
    conditionsPlaceholder: 'مثلاً: السكري، الضغط، لا يوجد',
    medsPlaceholder: 'مثلاً: أسبرين ١٠٠ ملجم، لا يوجد',
    criticalInfoWarning: 'هذه المعلومات حاسمة لحالات الطوارئ والعلاج الصحيح.',
    lifestyleTitle: 'نمط الحياة',
    habitsShapeSub: 'العادات التي تشكل صحتك',
    activityLevel: 'مستوى النشاط',
    dietType: 'نوع النظام الغذائي',
    avgSleep: 'متوسط النوم (ساعات)',
    smokingStatus: 'حالة التدخين',
    alcoholConsumption: 'استهلاك الكحول',
    geneticInfoTitle: 'المعلومات الجينية',
    compatibilitySub: 'مهم للتوافق',
    emergencyContactTitle: 'جهة اتصال طوارئ',
    whoContactSub: 'من يجب أن نتصل به؟',
    contactName: 'اسم جهة الاتصال',
    allSetTitle: 'أنت جاهز تماماً!',
    successCreatedSub: 'تم إنشاء هويتك الصحية الشخصية بنجاح.',
    enterMyHub: 'دخول ملتقى الصحة الخاص بي',
    // Lifestyle Options
    sedentary: 'خامل',
    light: 'خفيف',
    moderate: 'متوسط',
    veryActive: 'نشط جداً',
    regular: 'عادي',
    vegetarian: 'نباتي',
    vegan: 'نباتي صرف',
    keto: 'كيتو',
    never: 'أبداً',
    former: 'سابق',
    current: 'حالي',
    occasionally: 'أحياناً',
    moderately: 'باعتدال',
    frequently: 'بكثرة',

    // Navigation
    back: 'العودة',
    save: 'حفظ',
    cancel: 'إلغاء',
    next: 'التالي',
  }
};


export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'en' ? 'ar' : 'en'));
  };

  const t = (key) => translations[lang][key] || key;

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      <div className={lang === 'ar' ? 'rtl-theme' : 'ltr-theme'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
